### ISSUE TITLE
wrong min-datetime by using timezone and different date from utc

### ISSUE THREAD

**Issue by tsuchikazu** [mariomka/vue-datetime#114] opened 2018-12-03 10:53 UTC
## Versions
- vue: edge(2.5.17)
- vue-datetime: 1.0.0-beta.8
- luxon: 1.3.0

### Description:
I set `value-zone` and `zone` and `min-datetime` props. Timezone is `Asia/Tokyo`(UTC+09:00). 
`min-datetime` props is wrong work, when `min-datetime` props is set to a value that is different between utc date and date of specified time zone.

example

min-datetime | expect(Asia/Tokyo) | actual(Asia/Tokyo)
-- | -- | --
2018-12-10T14:59Z | 2018-12-10T23:59+09:00 | 2018-12-10T23:59+09:00
2018-12-10T15:00Z | 2018-12-11T00:00+09:00 | **2018-12-10T00:00+09:00**

Otherwise, an excellent component!
### Steps To Reproduce:
https://jsfiddle.net/5frzbmka/1/

**Comment by 1stevengrant** [comment] 2019-01-24 16:49
yeah, this has just bit us too

**Comment by sharik709** [comment] 2019-03-14 20:09
any possibility of this bug getting fixed anytime soon?

**Comment by sharik709** [comment] 2019-03-24 21:39
Hi @tsuchikazu , I had several issues with this plugin. You've mentioned one of them. Haven't received any response from anyone to solve this problem. So, I forked this repository and fixed problems like you mentioned. Please take a look and let me know if that resolves your issue. https://github.com/sharik709/vue-datetime

**Comment by signmein** [comment] 2019-04-24 23:43
I have this issue as well. When I switch my machine's zone into "UTC+8", I can still select the previous day. But the issue is not present in "UTC-4".

For example, in UTC+8 today is 2019/04/25, I should not be able to select 2019/04/24 in this case.

You can check my own fiddle here: https://jsfiddle.net/signmein/bam2n0kq/4/.

**Comment by saisagar89** [comment] 2019-06-18 17:59
> Hi @tsuchikazu , I had several issues with this plugin. You've mentioned one of them. Haven't received any response from anyone to solve this problem. So, I forked this repository and fixed problems like you mentioned. Please take a look and let me know if that resolves your issue. https://github.com/sharik709/vue-datetime

How can I install this library into my vue application
Thank you

**Comment by rsalunga29** [comment] 2019-08-08 17:10
I'm having this same problem to, setting `value-zone` and `zone` to "local" or my timezone doesn't fix it. Any update from the devs regarding the fix for this issue?

**Comment by rsalunga29** [comment] 2019-08-08 17:25
Okay, so I've found a work around to fix this problem, I simply put `.toLocalISOString()` on my `:min-datetime` and `:max-datetime` attributes.

Example below
`<datetime input-class="input" :min-datetime="new Date(min_date).toISOString()" :max-datetime="new Date(max_date).toISOString()" value-zone="local" zone="local"></datetime>`

**Comment by mariomka** [comment] 2019-11-13 13:11
It is fixed in the last version.

**Closed as completed by mariomka** 2019-11-13 13:11 UTC
Labels: bug
